/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Flier: typeof import('./components/Flier.vue')['default']
    Notification: typeof import('./components/Notification.vue')['default']
    Paragraphs: typeof import('./components/Paragraphs.vue')['default']
    ResetButton: typeof import('./components/ResetButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
